server:
  port: 8081

spring:
  application:
    name: spring-ai-demo
  logging:
    config: classpath:logback-spring.xml
  ai:
    zhipuai:
      api-key: ${ZHIPU_KEY:default_key}
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model:  ${AI_MODEL:glm-4-flash}